# PRETTIER CONFIGS (https://prettier.io/docs/options)
arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: "auto"
experimentalOperatorPosition: "start"
htmlWhitespaceSensitivity: "css"
jsxSingleQuote: false
objectWrap: "preserve"
quoteProps: "consistent"
semi: true
singleAttributePerLine: false
singleQuote: false
tabWidth: 2
trailingComma: "es5"
