# PRETTIER CONFIGS (https://prettier.io/docs/configuration)
arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: "auto"
htmlWhitespaceSensitivity: "css"
jsxSingleQuote: false
quoteProps: "consistent"
semi: true
singleAttributePerLine: false
singleQuote: false
tabWidth: 2
trailingComma: "es5"
