---
branches:
  - main
  - { name: next, prerelease: true }
tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - { breaking: true, release: major }
        - { type: feat, release: minor }
        - { type: refactor, scope: "core*", release: minor }
        - { revert: true, release: patch }
        - { type: build, release: patch }
        - { type: ci, release: patch }
        - { type: deps, release: patch }
        - { type: fix, release: patch }
        - { type: perf, release: patch }
        - { type: refactor, release: patch }
        - { type: chore, release: false }
        - { type: docs, release: false }
        - { type: style, release: false }
        - { scope: no-release, release: false }

  - - "@semantic-release/release-notes-generator"
    - preset: angular
      writerOpts:
        # This 'headerPartial' changes '#' to '##' for the release header (source template below).
        # https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/src/templates/header.hbs
        headerPartial: |-
          ## {{#if @root.linkCompare~}}
            [{{version}}](
            {{~#if @root.repository~}}
              {{~#if @root.host}}{{~@root.host}}/{{~/if}}
              {{~#if @root.owner}}{{~@root.owner}}/{{~/if}}
              {{~@root.repository}}
            {{~else}}
              {{~@root.repoUrl}}
            {{~/if~}}
            /compare/{{previousTag}}...{{currentTag}})
          {{~else}}
            {{~version}}
          {{~/if}}
          {{~#if title}} "{{title}}"{{~/if}}
          {{~#if date}} ({{date}}){{/if}}

  - - "@semantic-release/npm"
    - npmPublish: true

  - - "@semantic-release/github"
    - addReleases: bottom
      assignees: trevor-anderson

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: |-
        # Changelog

        All notable changes to this project will be documented in this file.

        ---

  - - "@semantic-release/git"
    - message: "chore(release): version ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets:
        - "CHANGELOG.md"
        - "package.json"
        - "package-lock.json"
        - "npm-shrinkwrap.json"
